dataset:
  data_path: data/Cora
  dev_ratio: 0
  has_node_feat: false
  is_overwrite_precompute: true
  is_sample_subgraph: true
  is_save_split: false
  loader_name: GRANData
  name: Cora
  node_order: DFS
  num_fwd_pass: 1
  num_subgraph_batch: 2
  train_ratio: 1
device: cuda:0
exp_dir: exp/GRAN_Cora
exp_name: GRANMixtureBernoulli_Cora_2025-Jun-05-03-34-04_1774672
gpus:
- 0
model:
  block_size: 1
  dimension_reduce: true
  edge_weight: 1.0
  embedding_dim: 512
  has_attention: true
  hidden_dim: 512
  is_sym: true
  max_num_nodes: 3000
  name: GRANMixtureBernoulli
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  num_mix_component: 20
  sample_stride: 1
run_id: '1774672'
runner: GranRunner
save_dir: exp/GRAN_Cora/GRANMixtureBernoulli_Cora_2025-Jun-05-03-34-04_1774672
seed: 1234
test:
  batch_size: 10
  better_vis: true
  is_single_plot: false
  is_test_ER: false
  is_vis: true
  num_test_gen: 100
  num_vis: 20
  num_workers: 0
  test_model_dir: exp/GRAN_Cora/GRANMixtureBernoulli_Cora_2025-Jun-05-03-34-04_1774672
  test_model_name: model_snapshot_0048300.pth
  vis_num_row: 5
train:
  batch_size: 8
  display_iter: 10
  is_resume: false
  lr: 0.0001
  lr_decay: 0.1
  lr_decay_epoch:
  - 100000000
  max_epoch: 50000
  momentum: 0.9
  num_workers: 16
  optimizer: Adam
  resume_dir: ''
  resume_epoch: 5000
  resume_model: ''
  shuffle: true
  snapshot_epoch: 100
  valid_epoch: 50
  wd: 0.0
use_gpu: true
use_horovod: false
