exp_name: GRAN_Cora
exp_dir: /data/luy25/GRAN_Cora
runner: GranRunner
use_horovod: false
use_gpu: true
device: cuda:1
gpus: [1]
seed: 1234

dataset:
  loader_name: GRANData
  name: cora
  type: raw
  total_nodes: 2708
  data_path: data
  node_order: DFS             # k_core / BFS / degree_decent
  train_ratio: 1
  dev_ratio: 0
  num_subgraph_batch: 2        # number of subgraphs per mini-batch
  num_fwd_pass: 1
  has_node_feat: false
  is_save_split: false
  is_sample_subgraph: true     # sample subgraphs from the single Cora graph
  is_overwrite_precompute: true

model:
  name: GRANMixtureBernoulli
  num_mix_component: 20
  is_sym: true
  block_size: 1
  sample_stride: 1
  max_num_nodes: 3000
  num_nodes: 2708
  hidden_dim: 512
  embedding_dim: 512
  num_GNN_layers: 7
  num_GNN_prop: 1
  num_canonical_order: 1
  dimension_reduce: true
  has_attention: true
  edge_weight: 1.0e+0

train:
  optimizer: Adam
  lr_decay: 0.1
  lr_decay_epoch: [100000000]  # no decay
  num_workers: 16
  max_epoch: 50000
  batch_size: 8
  display_iter: 10
  snapshot_epoch: 100
  valid_epoch: 50
  lr: 1.0e-4
  wd: 0.0e-4
  momentum: 0.9
  shuffle: true
  is_resume: false
  resume_epoch: 5000
  resume_dir: ""               # exp/GRAN_Cora/your_exp_folder (if resuming)
  resume_model: ""             # model_snapshot_XXXXX.pth (if resuming)

test:
  batch_size: 1
  num_workers: 0
  num_test_gen: 1            # number of generated samples for Cora
  is_vis: true
  is_single_plot: false        # visualize `num_vis` samples in one image
  is_test_ER: false            # do not compare to Erdos–Rényi baseline by default
  num_vis: 20
  vis_num_row: 5               # visualize `num_vis` samples in `vis_num_row` rows
  better_vis: true
  test_model_dir: TBD
  test_model_name: TBD
